const POWERUP_EFFECT_TYPES = [
  "LEG_CRAMP",
  "RUNNERS_HIGH",
  "WRONG_TURN",
  "CAMPFIRE_REST",
  "RAINSTORM",
];

const SETTLEMENT_EFFECT_TYPES = [
  ...POWERUP_EFFECT_TYPES,
  "QUICKSAND",
  "LEECH",
  "UPRISING",
  "RALLY_FLAG",
  "COIN_FLIP",
  "GHOST_PEPPER",
  "UMBRELLA",
];

module.exports = { POWERUP_EFFECT_TYPES, SETTLEMENT_EFFECT_TYPES };
