const INTERSTITIAL_PLACEMENTS = new Set([
  "race_detail_exit",
  "race_results_exit",
]);
const INTERSTITIAL_PLATFORMS = new Set(["ios", "android"]);

const DAILY_LIMIT = 2;
const ACQUISITION_GRACE_MS = 72 * 60 * 60 * 1000;
const SESSION_GRACE_MS = 90 * 1000;
const COOLDOWN_MS = 8 * 60 * 60 * 1000;
const SHOW_WINDOW_MS = 60 * 60 * 1000;
const RESERVATION_WINDOW_MS = 24 * 60 * 60 * 1000;
const SESSION_MAX_AGE_MS = 24 * 60 * 60 * 1000;
const IMPRESSION_MAX_AGE_MS = 24 * 60 * 60 * 1000;
const IMPRESSION_FUTURE_SKEW_MS = 2 * 60 * 1000;
const SDK_CALLBACK_GRACE_MS = 30 * 1000;

module.exports = {
  INTERSTITIAL_PLACEMENTS,
  INTERSTITIAL_PLATFORMS,
  DAILY_LIMIT,
  ACQUISITION_GRACE_MS,
  SESSION_GRACE_MS,
  COOLDOWN_MS,
  SHOW_WINDOW_MS,
  RESERVATION_WINDOW_MS,
  SESSION_MAX_AGE_MS,
  IMPRESSION_MAX_AGE_MS,
  IMPRESSION_FUTURE_SKEW_MS,
  SDK_CALLBACK_GRACE_MS,
};
