const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const test = require("node:test");

const {
  buildManifest,
  collectRuntimeEnvironmentReads,
  verifyRuntimeEnvInventory,
} = require("../../scripts/generate-runtime-control-disposition");

test("runtime-control manifest has unique complete control records", () => {
  verifyRuntimeEnvInventory();
  const manifest = buildManifest();
  const ids = manifest.controls.map((control) => control.id);
  assert.equal(new Set(ids).size, ids.length);
  for (const control of manifest.controls) {
    for (const key of [
      "disposition", "permanentValue", "polarityDefault",
      "evidenceTimestamp", "deployFamily", "rollbackValue",
      "compatibilityConsumers", "adminExposed",
    ]) {
      assert.equal(Object.prototype.hasOwnProperty.call(control, key), true, `${control.id}.${key}`);
    }
  }
});

test("source inventory independently covers bracket, helper, string, and numeric env reads", () => {
  const inventory = collectRuntimeEnvironmentReads();
  for (const name of [
    "NODE_TEST_CONTEXT",
    "ASYNC_RACE_RESOLUTION_CONCURRENCY",
    "TEAM_POOL_MULT_SHORT",
    "SESSION_TOKEN_SECRET",
    "S3_REGION",
    "S3_PUBLIC_BASE_URL",
    "S3_AVATAR_PREFIX",
    "S3_PRESIGNED_URL_EXPIRES_SECONDS",
  ]) {
    assert.equal(inventory.has(name), true, name);
  }
  const manifestByName = new Map(
    buildManifest().controls
      .filter((control) => control.id.startsWith("env:"))
      .map((control) => [control.name, control]),
  );
  for (const name of inventory.keys()) {
    assert.equal(manifestByName.has(name), true, `env:${name}`);
  }
  assert.equal(
    manifestByName.get("ASYNC_RACE_RESOLUTION_CONCURRENCY").kind,
    "numeric_environment",
  );
  assert.equal(
    manifestByName.get("SESSION_TOKEN_SECRET").kind,
    "string_environment",
  );
});

test("a newly discovered env read fails until it has explicit metadata", () => {
  const fixtureRoot = fs.mkdtempSync(path.join(os.tmpdir(), "runtime-env-fixture-"));
  const fixture = path.join(fixtureRoot, "unclassified.js");
  fs.writeFileSync(
    fixture,
    'const sanitized = "x".replace(/[!\'()*]/g, "");\n' +
      'module.exports = [sanitized, process.env.NEW_UNCLASSIFIED_CONTROL];\n',
  );
  try {
    assert.throws(
      () => verifyRuntimeEnvInventory({ directories: [fixtureRoot] }),
      /NEW_UNCLASSIFIED_CONTROL.*explicit envMetadata/,
    );
  } finally {
    fs.rmSync(fixtureRoot, { recursive: true, force: true });
  }
});

test("checked-in runtime-control manifest is generated byte-for-byte", () => {
  const root = path.resolve(__dirname, "../..");
  const checkedIn = JSON.parse(
    fs.readFileSync(path.join(root, "docs/runtime-control-disposition.yaml"), "utf8"),
  );
  assert.deepEqual(checkedIn, buildManifest());
});
