require('./adminRedisFixture.cjs');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {before,beforeEach,after,it}=require('node:test');
const {cleanDatabase,createTestUser,startServer,prisma,request}=require('./setup');
const {appSettings}=require('../../src/shared/config/appSettings');
let server,admin,clock=new Date();const events=[];const sourceStatements=[];
const hints={overview:'dashboard-summary',growth:'dashboard-growth',activity:'dashboard-dau-engagement',retention:'dashboard-summary',races:'dashboard-summary',invites:'dashboard-funnels',onboarding:'dashboard-funnels',ads:'dashboard-revenue',shop:'economy'};
before(async()=>{const {pool}=require('../../src/db');const measuredPool={connect:async()=>{const c=await pool.connect();return new Proxy(c,{get(t,k){if(k==='query')return async(sql,...args)=>{if(typeof sql==='string'&&/^(DECLARE|FETCH)/.test(sql))sourceStatements.push(sql);return t.query(sql,...args);};return typeof t[k]==='function'?t[k].bind(t):t[k];}});}};server=await startServer({pool:measuredPool,adminAnalyticsNow:()=>clock,adminAnalyticsObserver:e=>events.push(e)});});
after(async()=>{await server?.close();});
beforeEach(async()=>{await cleanDatabase();events.length=0;sourceStatements.length=0;clock=new Date();await appSettings.setFlag('adminMetricsV2TelemetryEnabled',false);admin=await createTestUser({email:'admin@test.com'});});
async function page(view,window='7d'){const r=await request(server.baseUrl,'GET',`/admin/stats?view=${view}&window=${window}&sections=${hints[view]||'dashboard-summary'}`,{token:admin.token});return {status:r.status,body:await r.json()};}
it('validates view before any analytics extraction',async()=>{const r=await page('unknown');assert.equal(r.status,400);assert.equal(r.body.code,'INVALID_ADMIN_VIEW');assert.equal(events.filter(e=>e.event==='query').length,0);});
for(const view of Object.keys(hints))it(`returns one projected ${view} page and warm cache performs no source reads`,async()=>{
 const first=await page(view);assert.equal(first.status,200,JSON.stringify({body:first.body,events}));assert.equal(first.body.stats.view,view);assert.ok(first.body.stats.sections[hints[view]]);assert.ok(events.some(e=>e.event==='pageSource'),'cold page must actually extract declared sources');
 const executed=sourceStatements.length;assert.ok(executed>0,'cold page executes real cursor statements');const count=events.filter(e=>e.event==='pageSource').length;const second=await page(view);assert.equal(second.status,200);assert.equal(second.body.stats.generatedAt,first.body.stats.generatedAt);assert.equal(events.filter(e=>e.event==='pageSource').length,count);assert.equal(sourceStatements.length,executed,'warm page executes zero real source statements');
 const sources=events.filter(e=>e.event==='pageSource').map(e=>e.source);
 if(view==='ads')assert.deepEqual([...new Set(sources)],['ads']);
 if(view==='shop')assert.deepEqual([...new Set(sources)],['shopPowerups','shopItems']);
 if(view==='overview')for(const forbidden of ['retentionActivity','repeatRaces','friends','shopItems','invites','onboarding'])assert.ok(!sources.includes(forbidden));
});
it('streams more than 200000 repeated events with exact union and bounded acknowledged batches',async()=>{
 const buyer=await createTestUser({email:'stream-buyer@test.com'});const race=await prisma.race.create({data:{creatorId:buyer.user.id,name:'Stream actions',targetSteps:1000,status:'ACTIVE'}});
 await prisma.$executeRaw`INSERT INTO race_powerup_events(id,race_id,actor_user_id,event_type,description,created_at) SELECT 'stream-box-'||n,${race.id},${buyer.user.id},'MYSTERY_BOX_OPENED','Repeated box',now() FROM generate_series(1,210000)n`;
 const r=await page('activity');assert.equal(r.status,200,JSON.stringify(r.body));const d=r.body.stats.sections['dashboard-dau-engagement'].metricsDashboard.dauEngagement;assert.deepEqual(d.today.actions.boxOpen,{users:1,events:210000});assert.equal(d.actionBasedDau.users,1);
 const batches=events.filter(e=>e.event==='pageBatch');assert.ok(batches.length>105);assert.ok(batches.every(e=>e.rows<=2000&&e.outstanding===1));const done=events.find(e=>e.event==='pageComplete');assert.ok(done.streamedRows>200000);assert.ok(done.stateBytes<64*1024*1024);
});
const dateOf=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York'}).format(d);
const shiftDate=(d,n)=>new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
async function epochAt(at){await prisma.adminMetricsCollectionEpoch.updateMany({where:{endedAt:null},data:{endedAt:clock}});return prisma.adminMetricsCollectionEpoch.create({data:{startedAt:new Date(at)}});}
async function activity(userId,date){return prisma.userActivityDay.create({data:{userId,activityDate:new Date(date),firstSeenAt:clock,lastSeenAt:clock,appVersion:'2.5.0',metadataOccurredAt:clock}});}
it('Growth 7d includes true trailing MAU while Overview 7d projects only its needed week',async()=>{
 const end=dateOf(clock),epoch=await epochAt(shiftDate(end,-100)+'T04:00:00Z');const u=await createTestUser({email:'mau@test.com'});await prisma.user.update({where:{id:u.user.id},data:{createdAt:new Date(shiftDate(end,-20)+'T12:00:00Z'),metricsV2EligibleEpochId:epoch.id,metricsV2EligibleAt:new Date(shiftDate(end,-40)+'T12:00:00Z')}});await activity(u.user.id,shiftDate(end,-20));
 const g=(await page('growth')).body.stats.sections['dashboard-growth'].metricsDashboard.userGrowth;assert.equal(g.observedForegroundMau,1);assert.equal(g.observedForegroundWau,0);assert.equal(g.daily.length,7);
 const o=(await page('overview')).body.stats.sections;assert.equal(o['dashboard-growth'].metricsDashboard.userGrowth.observedForegroundMau,undefined);assert.equal(o['dashboard-summary'].metricsDashboard.summary.retention,undefined);
});
it('projects exact mature retention pooled cohorts and historical first-race semantics',async()=>{
 const end=dateOf(clock),epoch=await epochAt(shiftDate(end,-150)+'T04:00:00Z');const user=await createTestUser({email:'cohort@test.com'});const signup=shiftDate(end,-40);await prisma.user.update({where:{id:user.user.id},data:{createdAt:new Date(signup+'T12:00:00Z'),metricsV2SignupEligible:true,metricsV2SignupEpochId:epoch.id}});await activity(user.user.id,shiftDate(signup,1));await activity(user.user.id,shiftDate(signup,30));
 // Earlier historical first race outside90days prevents a later completion
 // from being misclassified as this user's first qualifying race.
 for(const [n,age]of [[1,120],[2,40]]){const r=await prisma.race.create({data:{creatorId:user.user.id,name:'Historical '+n,targetSteps:1000,status:'COMPLETED',createdAt:new Date(shiftDate(end,-age-2)+'T12:00:00Z'),startedAt:new Date(shiftDate(end,-age-1)+'T12:00:00Z'),completedAt:new Date(shiftDate(end,-age)+'T12:00:00Z')}});await prisma.raceParticipant.create({data:{raceId:r.id,userId:user.user.id,status:'ACCEPTED',joinedAt:new Date(shiftDate(end,-age-2)+'T12:00:00Z'),finishedAt:new Date(shiftDate(end,-age)+'T12:00:00Z')}});}
 const r=await page('retention');assert.equal(r.status,200,JSON.stringify(r.body));const s=r.body.stats.sections;assert.deepEqual(s['dashboard-summary'].metricsDashboard.summary.retention,{d1:{numerator:1,denominator:1,percent:100},d7:{numerator:0,denominator:1,percent:0},d30:{numerator:1,denominator:1,percent:100}});assert.equal(s['dashboard-retention'].metricsDashboard.retention.cohorts.length,7);assert.equal(s['dashboard-retention'].metricsDashboard.retention.cohorts.at(-1).d1.percent,null);assert.equal(s['dashboard-retention-mature'].metricsDashboard.window.days,90);assert.equal(s['dashboard-retention-mature'].metricsDashboard.retention.secondRaceWithin30d.denominator,0);
});
it('Ads preserves retained review-free daily watchers but legacy latest recorded grant-day cap population',async()=>{
 const user=await createTestUser({email:'ads@test.com'}),review=await createTestUser({email:'review-ads@test.com'});await prisma.user.update({where:{id:review.user.id},data:{isReviewAccount:true}});const end=dateOf(clock);
 const grants=[];for(let i=0;i<20;i++)grants.push({userId:user.user.id,transactionId:randomUUID(),rewardKind:'coin_reward',grantedDate:shiftDate(end,-1),createdAt:clock});for(let i=0;i<20;i++)grants.push({userId:review.user.id,transactionId:randomUUID(),rewardKind:'coin_reward',grantedDate:end,createdAt:clock});grants.push({userId:user.user.id,transactionId:randomUUID(),rewardKind:'box_reroll',grantedDate:end,createdAt:clock});await prisma.adRewardGrant.createMany({data:grants});
 const r=await page('ads');assert.equal(r.status,200);const s=r.body.stats.sections,d=s['dashboard-revenue'].metricsDashboard.revenue.daily.at(-1);assert.equal(d.uniqueSsvWatchers,1);assert.equal(d.ssvGrants,21);assert.equal(d.ssvByRewardKind.find(k=>k.rewardKind==='box_reroll').grants,1);assert.equal(s.ads.adRevenue.capUtilization.usersAtCap,1);
});
it('Shop popularity counts acquisitions including free ownership rows rather than purchase-history provenance',async()=>{
 const user=await createTestUser({email:'shop-popularity@test.com'});const item=await prisma.shopItem.create({data:{id:randomUUID(),sku:'free-acquisition',name:'Free hat',slot:'HEAD',priceCoins:0,assetKey:'test.png'}});await prisma.userShopItem.create({data:{userId:user.user.id,shopItemId:item.id,purchasedAt:clock}});await prisma.shopPurchaseRequest.create({data:{userId:user.user.id,shopItemId:item.id,idempotencyKey:randomUUID(),status:'SUCCEEDED',coinsSpent:0,resultJson:{purchase:{alreadyOwned:true,coinsSpent:0}}}});
 const r=await page('shop');assert.equal(r.status,200);assert.deepEqual(r.body.stats.sections.economy.coinEconomy.purchasesBySku,[{sku:'free-acquisition',count:1}]);
});
it('uses true ET midnight for foreground eligibility and action buckets across both DST changes',async()=>{
 for(const [date,at,eligibleAt,expected]of [['2026-03-08','2026-03-08T05:00:00Z','2026-03-08T04:30:00Z',1],['2026-11-01','2026-11-01T04:00:00Z','2026-11-01T04:30:00Z',0]]){
 clock=new Date(date+'T16:00:00Z');const epoch=await epochAt(at),u=await createTestUser({email:'page-dst-'+date+'@test.com'});await prisma.user.update({where:{id:u.user.id},data:{metricsV2EligibleEpochId:epoch.id,metricsV2EligibleAt:new Date(eligibleAt)}});await activity(u.user.id,date);
 const r=await page('overview');assert.equal(r.status,200);const s=r.body.stats.sections['dashboard-summary'].metricsDashboard;assert.equal(s.coverage.metricCoverage.observedForegroundDau.eligible,expected);assert.equal(s.summary.growth.observedForegroundDau,expected);
 }
});
it('isolates overlapping summary projections and range caches, rejects unauthorized warm hits, and evicts disabled data',async()=>{
 const a=await page('overview'),b=await page('retention');assert.equal(a.body.stats.sections['dashboard-summary'].metricsDashboard.summary.retention,undefined);assert.ok(b.body.stats.sections['dashboard-summary'].metricsDashboard.summary.retention);const month=await page('overview','30d');assert.equal(month.body.stats.sections['dashboard-growth'].metricsDashboard.userGrowth.daily.length,30);
 const ordinary=await createTestUser({email:'unauthorized@test.com'});for(const [token,status]of [[undefined,401],[ordinary.token,403]])assert.equal((await request(server.baseUrl,'GET','/admin/stats?view=overview&sections=dashboard-summary',{token})).status,status);
 clock=new Date(clock.getTime()+901000);const stale=await page('overview');assert.equal(stale.body.stats.snapshot.status,'stale');assert.equal(stale.body.stats.generatedAt,a.body.stats.generatedAt);await appSettings.setFlag('adminMetricsV2DashboardEnabled',false);const disabled=await page('overview');assert.equal(disabled.body.stats.sections['dashboard-summary'].metricsDashboard.status,'disabled');assert.equal(disabled.body.stats.sections['dashboard-summary'].metricsDashboard.summary,undefined);await appSettings.setFlag('adminMetricsV2DashboardEnabled',true);
});
it('deduplicates a cold page across HTTP workers and shares completed payloads',async()=>{
 const peer=await startServer({adminAnalyticsNow:()=>clock,adminAnalyticsObserver:e=>events.push(e)});
 try{const path='/admin/stats?view=overview&window=7d&sections=dashboard-summary';const replies=await Promise.all([server,peer,server,peer].map(s=>request(s.baseUrl,'GET',path,{token:admin.token})));assert.ok(replies.every(r=>r.status===200));const bodies=await Promise.all(replies.map(r=>r.json()));assert.equal(new Set(bodies.map(b=>b.stats.generatedAt)).size,1);assert.equal(events.filter(e=>e.event==='pageComplete').length,1);}finally{await peer.close();}
});
it('keeps local completed page on Redis failure and refuses cold source reads',async()=>{
 const first=await page('ads');assert.equal(first.status,200);const cache=require('../../src/shared/cache/redisCache'),original=cache.evalLua;const before=events.filter(e=>e.event==='query').length;cache.evalLua=async()=>({ok:false,disabled:false,result:null});try{const warm=await page('ads');assert.equal(warm.status,200);assert.equal(warm.body.stats.generatedAt,first.body.stats.generatedAt);const cold=await page('activity');assert.equal(cold.status,503);assert.equal(cold.body.code,'ADMIN_ANALYTICS_UNAVAILABLE');assert.equal(events.filter(e=>e.event==='query').length,before);}finally{cache.evalLua=original;}
});
it('terminates a failed worker, closes transaction cursors, and isolates page backoff',async()=>{
 const {EventEmitter}=require('node:events'),{pool}=require('../../src/db');const statements=[];let releases=0;
 const trackedPool={connect:async()=>{const c=await pool.connect();return new Proxy(c,{get(t,k){if(k==='query')return async(...args)=>{statements.push(args[0]);return t.query(...args);};if(k==='release')return()=>{releases++;return t.release();};return typeof t[k]==='function'?t[k].bind(t):t[k];}});}};
 let terminated=0;const faulty=await startServer({pool:trackedPool,adminAnalyticsNow:()=>clock,adminAnalyticsObserver:e=>events.push(e),adminPageWorkerFactory:()=>{const w=new EventEmitter();w.postMessage=message=>setImmediate(()=>w.emit('message',{id:message.id,error:'Injected worker failure'}));w.terminate=async()=>{terminated++;};setImmediate(()=>w.emit('message',{id:0,ack:true}));return w;}});
 try{const r=await request(faulty.baseUrl,'GET','/admin/stats?view=overview&sections=dashboard-summary&window=7d',{token:admin.token});assert.equal(r.status,503);assert.equal((await r.json()).code,'ADMIN_ANALYTICS_UNAVAILABLE');assert.equal(terminated,1);assert.ok(statements.includes('ROLLBACK'));assert.ok(releases>=2);assert.equal((await page('ads')).status,200);const count=events.filter(e=>e.event==='pageSource').length;assert.equal((await page('overview')).status,503);assert.equal(events.filter(e=>e.event==='pageSource').length,count);}finally{await faulty.close();}
});
it('missing worker ACK returns pending below client timeout then aborts and releases the cursor at the build deadline',async()=>{
 const {EventEmitter}=require('node:events'),{pool}=require('../../src/db');let rolledBack=false,releasedAfterRollback=false,terminated=false;const faultEvents=[];
 const trackedPool={connect:async()=>{const c=await pool.connect();return new Proxy(c,{get(t,k){if(k==='query')return async(...args)=>{if(args[0]==='ROLLBACK')rolledBack=true;return t.query(...args);};if(k==='release')return()=>{if(rolledBack)releasedAfterRollback=true;return t.release();};return typeof t[k]==='function'?t[k].bind(t):t[k];}});}};
 const faulty=await startServer({pool:trackedPool,adminAnalyticsNow:()=>clock,adminAnalyticsObserver:e=>faultEvents.push(e),adminPageWorkerFactory:()=>{const w=new EventEmitter();w.postMessage=()=>{};w.terminate=async()=>{terminated=true;};setImmediate(()=>w.emit('message',{id:0,ack:true}));return w;}});
 try{const started=Date.now(),r=await request(faulty.baseUrl,'GET','/admin/stats?view=overview&sections=dashboard-summary&window=7d',{token:admin.token});assert.equal(r.status,503);assert.equal((await r.json()).code,'ADMIN_ANALYTICS_PENDING');assert.ok(Date.now()-started<14000);assert.equal(r.headers.get('retry-after'),'15');while(Date.now()-started<48000&&!releasedAfterRollback)await new Promise(resolve=>setTimeout(resolve,100));assert.equal(terminated,true);assert.equal(rolledBack,true);assert.equal(releasedAfterRollback,true);assert.ok(faultEvents.some(e=>e.event==='failure'&&e.reason==='Analytics build deadline exceeded'));assert.equal((await page('overview')).body.code,'ADMIN_ANALYTICS_UNAVAILABLE');}finally{await faulty.close();}
});
it('never publishes a completed page after losing its shared legacy/view lease',async()=>{
 const Redis=require('ioredis'),redis=new Redis(process.env.REDIS_URL);let stolen=false;const observed=[];const key=process.env.CACHE_ENV_PREFIX+'admin:analytics:v1:lease';
 const attacker=await startServer({adminAnalyticsNow:()=>clock,adminAnalyticsObserver:e=>{observed.push(e);if(e.event==='pageSource'&&!stolen){stolen=true;redis.set(key,'other-owner','PX',60000);}}});
 try{const r=await request(attacker.baseUrl,'GET','/admin/stats?view=overview&window=7d&sections=dashboard-summary',{token:admin.token});assert.equal(r.status,503);assert.equal((await redis.keys(process.env.CACHE_ENV_PREFIX+'admin:analytics:views:v1:*')).length,0);assert.ok(observed.some(e=>e.event==='failure'));assert.equal(await redis.get(key),'other-owner');}finally{await redis.del(key);redis.disconnect();await attacker.close();}
});
async function legacy(section){const r=await request(server.baseUrl,'GET',`/admin/stats?sections=${section}&window=7d`,{token:admin.token});assert.equal(r.status,200);return (await r.json()).stats.metricsDashboard;}
it('Races projects the same live overlap, visibility, current counts and friendship ratios as the released contract',async()=>{
 const u=await createTestUser({email:'race-page@test.com'}),other=await createTestUser({email:'race-friend@test.com'});const end=dateOf(clock);
 const race=await prisma.race.create({data:{creatorId:u.user.id,name:'Visible race',targetSteps:1000,status:'ACTIVE',isPublic:true,createdAt:clock,startedAt:new Date(shiftDate(end,-2)+'T12:00:00Z')}});await prisma.raceParticipant.create({data:{userId:u.user.id,raceId:race.id,status:'ACCEPTED',joinedAt:clock}});await prisma.friendship.create({data:{requesterId:u.user.id,addresseeId:other.user.id,status:'ACCEPTED'}});
 const r=await page('races');assert.equal(r.status,200,JSON.stringify(r.body));const s=r.body.stats.sections;const summary=await legacy('dashboard-summary'),engagement=await legacy('dashboard-engagement'),activation=await legacy('dashboard-activation');
 for(const key of ['usersInActiveNonFeaturedRaces','activeNonFeaturedRaces','activeDailyRaces'])assert.equal(s['dashboard-summary'].metricsDashboard.summary.races[key],summary.summary.races[key]);
 const e=s['dashboard-engagement'].metricsDashboard.raceEngagement;assert.deepEqual(e.daily,engagement.raceEngagement.daily.map(({date,liveRaceParticipants})=>({date,liveRaceParticipants})));assert.deepEqual(e.visibility,engagement.raceEngagement.visibility);assert.equal(e.rankedParticipationUsers,engagement.raceEngagement.rankedParticipationUsers);for(const cadence of ['daily','weekly'])for(const key of ['activeOverlapUsers','joinedWindowUsers'])assert.equal(e.featuredParticipation[cadence][key],engagement.raceEngagement.featuredParticipation[cadence][key]);assert.deepEqual(s['dashboard-activation'].metricsDashboard.activation.friends,activation.activation.friends);
});
it('Invites keeps adjacent-event 24h deduplication and Onboarding keeps mature session stages without loading each other',async()=>{
 const oldVersion=process.env.REFERRAL_IP_HMAC_ACTIVE_VERSION,oldSecret=process.env.REFERRAL_IP_HMAC_SECRET_V91;process.env.REFERRAL_IP_HMAC_ACTIVE_VERSION='91';process.env.REFERRAL_IP_HMAC_SECRET_V91='test-only-hmac-secret-for-admin-page-91';
 try{const end=dateOf(clock),start=new Date(shiftDate(end,-5)+'T12:00:00Z');await prisma.metricCoverageStart.create({data:{metric:'referralHmacV91',operationalAt:new Date(shiftDate(end,-20)+'T12:00:00Z')}});const owner=await createTestUser({email:'invite-owner@test.com'}),referee=await createTestUser({email:'invite-referee@test.com'});await prisma.user.update({where:{id:owner.user.id},data:{referralCode:'PAGE91'}});await prisma.referral.create({data:{referrerId:owner.user.id,refereeId:referee.user.id,refereeSubHash:randomUUID(),status:'REWARDED',code:'PAGE91'}});
 await prisma.linkOpen.createMany({data:[0,20,40].map(h=>({kind:'referral',code:'PAGE91',ipHash:'same-hash',ipHashVersion:91,createdAt:new Date(start.getTime()+h*3600000)}))});
 const session=randomUUID();await prisma.activationEvent.createMany({data:[['onboarding_started',0,{}],['health_cta_tapped',1,{}],['health_result',2,{result:'granted'}],['health_escaped',3,{}],['tutorial_skipped',4,{}],['home_reached',5,{}],['home_reached',6,{}]].map(([name,m,context])=>({id:randomUUID(),userId:referee.user.id,onboardingSessionId:session,name,context,appVersion:'2.5.0',platform:'ios',occurredAt:new Date(start.getTime()+m*60000)}))});
 const invite=await page('invites'),onboarding=await page('onboarding');assert.equal(invite.status,200,JSON.stringify(invite.body));assert.equal(onboarding.status,200,JSON.stringify(onboarding.body));const full=await legacy('dashboard-funnels');assert.deepEqual(invite.body.stats.sections['dashboard-funnels'].metricsDashboard.inviteFunnel,full.inviteFunnel);assert.equal(full.inviteFunnel.uniqueLinkOpens,1);assert.deepEqual(onboarding.body.stats.sections['dashboard-funnels'].metricsDashboard.onboardingFunnel,full.onboardingFunnel);const sources=events.filter(e=>e.event==='pageSource');assert.ok(!sources.some(e=>e.view==='invites'&&e.source.startsWith('onboarding')));assert.ok(!sources.some(e=>e.view==='onboarding'&&e.source.startsWith('invite')));
 }finally{if(oldVersion===undefined)delete process.env.REFERRAL_IP_HMAC_ACTIVE_VERSION;else process.env.REFERRAL_IP_HMAC_ACTIVE_VERSION=oldVersion;if(oldSecret===undefined)delete process.env.REFERRAL_IP_HMAC_SECRET_V91;else process.env.REFERRAL_IP_HMAC_SECRET_V91=oldSecret;}
});
it('rejects prototype names and non-scalar view/window parameters with public validation codes',async()=>{
 for(const [query,code]of [['view=constructor','INVALID_ADMIN_VIEW'],['view=__proto__','INVALID_ADMIN_VIEW'],['view=toString','INVALID_ADMIN_VIEW'],['view=overview&window=constructor','INVALID_WINDOW'],['view=overview&window=__proto__','INVALID_WINDOW'],['view=overview&view=ads','INVALID_ADMIN_VIEW'],['view=overview&window=7d&window=30d','INVALID_WINDOW']]){const r=await request(server.baseUrl,'GET','/admin/stats?'+query,{token:admin.token});assert.equal(r.status,400);assert.equal((await r.json()).code,code);}
});
it('uses the same global lease for legacy and view builds without overlapping analytics work',async()=>{
 let active=0,max=0;const {pool}=require('../../src/db');const wrappedPool={connect:async()=>{const c=await pool.connect();let building=false;return new Proxy(c,{get(t,k){if(k==='query')return async(sql,...args)=>{if(typeof sql==='string'&&sql.startsWith('BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ')){if(!building){building=true;active++;max=Math.max(max,active);}await new Promise(resolve=>setTimeout(resolve,100));}return t.query(sql,...args);};if(k==='release')return()=>{if(building){active--;building=false;}return t.release();};return typeof t[k]==='function'?t[k].bind(t):t[k];}});}};
 const a=await startServer({pool:wrappedPool,adminAnalyticsNow:()=>clock}),b=await startServer({pool:wrappedPool,adminAnalyticsNow:()=>clock});try{const responses=await Promise.all([request(a.baseUrl,'GET','/admin/stats?view=overview&window=7d&sections=dashboard-summary',{token:admin.token}),request(b.baseUrl,'GET','/admin/stats?sections=dashboard-dau-engagement&window=7d',{token:admin.token})]);assert.ok(responses.every(r=>r.status===200));assert.equal(max,1);assert.equal(active,0);}finally{await a.close();await b.close();}
});
it('keeps cold waiting below client timeout even when successive Redis reads consume the remaining deadline',async()=>{
 const Redis=require('ioredis'),redis=new Redis(process.env.REDIS_URL),cache=require('../../src/shared/cache/redisCache'),original=cache.evalLua,key=process.env.CACHE_ENV_PREFIX+'admin:analytics:v1:lease';await redis.set(key,'existing-legacy-owner','PX',60000);cache.evalLua=async(...args)=>{await new Promise(resolve=>setTimeout(resolve,1200));return original(...args);};try{const at=Date.now(),r=await page('overview');assert.equal(r.status,503);assert.equal(r.body.code,'ADMIN_ANALYTICS_PENDING');assert.ok(Date.now()-at<11500);assert.equal(events.filter(e=>e.event==='pageSource').length,0);}finally{cache.evalLua=original;await new Promise(resolve=>setTimeout(resolve,1300));await redis.del(key);redis.disconnect();}
});
it('invalidates invite snapshots when configured HMAC version changes without a database configuration change',async()=>{
 const saved=Object.fromEntries(['REFERRAL_IP_HMAC_ACTIVE_VERSION','REFERRAL_IP_HMAC_SECRET_V91','REFERRAL_IP_HMAC_SECRET_V92'].map(k=>[k,process.env[k]]));process.env.REFERRAL_IP_HMAC_SECRET_V91='test-only-hmac-secret-for-admin-page-91';process.env.REFERRAL_IP_HMAC_SECRET_V92='test-only-hmac-secret-for-admin-page-92';process.env.REFERRAL_IP_HMAC_ACTIVE_VERSION='91';
 try{const end=dateOf(clock),owner=await createTestUser({email:'version-owner@test.com'});await prisma.user.update({where:{id:owner.user.id},data:{referralCode:'VERSIONPAGE'}});await prisma.metricCoverageStart.createMany({data:[91,92].map(v=>({metric:'referralHmacV'+v,operationalAt:new Date(shiftDate(end,-20)+'T12:00:00Z')}))});await prisma.linkOpen.create({data:{kind:'referral',code:'VERSIONPAGE',ipHash:'h',ipHashVersion:91,createdAt:clock}});const first=await page('invites');assert.equal(first.body.stats.sections['dashboard-funnels'].metricsDashboard.inviteFunnel.linkOpens,1);process.env.REFERRAL_IP_HMAC_ACTIVE_VERSION='92';const next=await page('invites');assert.equal(next.body.stats.sections['dashboard-funnels'].metricsDashboard.inviteFunnel.linkOpens,0);assert.equal(events.filter(e=>e.event==='pageComplete').length,2);}finally{for(const[k,v]of Object.entries(saved))if(v===undefined)delete process.env[k];else process.env[k]=v;}
});
