const assert=require('node:assert/strict');
const {before,after,beforeEach,it}=require('node:test');
const {cleanDatabase,prisma,request,startServer,createTestUser}=require('../setup');
let server,history;
const config={projectId:'proj_bara',secretApiKey:'integration-only',webhookAuthorization:'Bearer integration-webhook',iosAppId:'app_ios',androidAppId:'app_android',termsUrl:'https://steptracker-api.org/billing-terms.html',privacyUrl:'https://steptracker-api.org/privacy.html'};
before(async()=>{server=await startServer({billingConfig:config,billingProvider:{async getCustomerHistory(){if(history instanceof Error)throw history;return history;}}});});
after(async()=>{await server.close();});
beforeEach(async()=>{await cleanDatabase();history={purchases:[],subscriptions:[],observedAt:new Date().toISOString()};});
const iso=n=>new Date(n).toISOString();
function permanent(overrides={}){return {transactionId:'permanent1',providerId:'p1',productId:'plus_permanent',appId:'app_ios',store:'app_store',environment:'production',purchasedAt:iso(Date.now()-1000),expiresAt:null,quantity:1,paid:true,purchaseStatus:'owned',refunded:false,subscriptionId:null,...overrides};}
async function boot(token){const r=await request(server.baseUrl,'GET','/billing/bootstrap?platform=ios',{token});assert.equal(r.status,200);return r.json();}
async function sync(token,transactionId){const r=await request(server.baseUrl,'POST','/billing/sync?platform=ios',{token,body:transactionId?{transactionId}:{}});return {status:r.status,body:await r.json()};}
async function event(identity,id,type,at=Date.now(),tx='permanent1'){const r=await request(server.baseUrl,'POST','/billing/webhook/revenuecat',{headers:{Authorization:config.webhookAuthorization},body:{event:{id,type,cancel_reason:type==='CANCELLATION'?'CUSTOMER_SUPPORT':undefined,app_user_id:identity,app_id:'app_ios',store:'APP_STORE',environment:'PRODUCTION',product_id:'bara_plus_permanent_v1',transaction_id:tx,event_timestamp_ms:at}}});assert.equal(r.status,200);}
function monthly(start,end,annual=false){history.subscriptions=[{providerId:'sub1',productId:annual?'plus_annual':'plus_monthly',appId:'app_ios',store:'app_store',environment:'production',startsAt:start,periodStartsAt:start,accessUntil:end,givesAccess:true,trial:false,status:'active',renews:true,managementUrl:'https://apps.apple.com/account/subscriptions'}];return permanent({transactionId:'monthly1',productId:annual?'plus_annual':'plus_monthly',subscriptionId:'sub1',purchasedAt:start,expiresAt:end});}
it('offers monthly and non-consumable permanent, retiring annual sale identifiers',async()=>{const {token}=await createTestUser();const b=await boot(token);assert.deepEqual(b.products.map(p=>p.id),['coins_500','coins_2800','coins_6000','plus_monthly','plus_permanent']);assert.deepEqual(b.products.at(-1),{id:'plus_permanent',kind:'non_consumable',coins:500,credits:10,plan:'permanent',storeProductId:'bara_plus_permanent_v1'});});
it('activates permanent once and grants period zero through one immutable schedule',async()=>{
 const {token}=await createTestUser();const b=await boot(token);history.purchases=[permanent()];let result=await sync(token,'permanent1');assert.equal(result.status,200);assert.equal(result.body.coins,500);assert.equal(result.body.credits.paid,10);assert.equal(result.body.membership.plan,'permanent');assert.equal(result.body.membership.accessUntil,null);assert.equal(result.body.membership.renews,false);assert.equal(result.body.membership.subscription,null);assert.ok(result.body.membership.nextRewardAt);assert.ok(result.body.products.every(p=>p.kind==='coins'));
 await Promise.all([sync(token,'permanent1'),sync(token,'permanent1')]);assert.equal((await boot(token)).coins,500);
 const receipt=await prisma.billingPurchase.findFirst({where:{identityId:b.identity.appUserId}});assert.equal(receipt.grantedCoins,0);assert.equal(receipt.grantedCredits,0);assert.equal(await prisma.billingPermanentGrant.count(),1);assert.equal(await prisma.billingPermanentSchedule.count(),1);
});
it('acknowledges delayed activation immediately while retaining subscription management and cosmetics',async()=>{
 const {token}=await createTestUser();await boot(token);const end=iso(Date.now()+25*86400000);const paid=monthly(iso(Date.now()-5*86400000),end);
 const item=await prisma.shopItem.create({data:{sku:'perm-month',name:'Month',slot:'HEAD',assetKey:'straw_hat',priceCoins:0}});await prisma.billingCosmeticRelease.create({data:{month:new Date().toISOString().slice(0,7),shopItemId:item.id}});
 history.purchases=[paid,permanent()];const result=await sync(token,'permanent1');assert.equal(result.status,200);assert.equal(result.body.coins,500);assert.equal(result.body.credits.paid,10);assert.equal(result.body.membership.nextRewardAt,end);assert.equal(result.body.membership.subscription.plan,'monthly');assert.equal(result.body.managementUrl,'https://apps.apple.com/account/subscriptions');assert.ok(result.body.cosmetic);assert.equal(await prisma.billingPermanentGrant.count(),0);
});
it('preserves historical annual payment benefits and delays the permanent anchor to its paid end',async()=>{const {token}=await createTestUser();await boot(token);const end=iso(Date.now()+360*86400000);history.purchases=[monthly(iso(Date.now()-5*86400000),end,true),permanent()];const r=await sync(token,'permanent1');assert.equal(r.status,200);assert.equal(r.body.coins,6000);assert.equal(r.body.credits.paid,120);assert.equal(r.body.membership.subscription.plan,'annual');assert.equal(r.body.membership.nextRewardAt,end);assert.ok(!r.body.products.some(p=>p.id==='plus_annual'));});
it('trial coverage does not delay the permanent bundle',async()=>{const {token}=await createTestUser();await boot(token);const trial=monthly(iso(Date.now()-1000),iso(Date.now()+7*86400000));history.subscriptions[0].trial=true;history.subscriptions[0].status='trialing';trial.paid=false;history.purchases=[trial,permanent()];const r=await sync(token,'permanent1');assert.equal(r.status,200);assert.equal(r.body.coins,500);assert.equal(r.body.credits.paid,10);assert.equal(r.body.credits.trial,0);});
it('catches up missed periods in bounded twelve-period transactions without discarding work',async()=>{
 const {token}=await createTestUser();const b=await boot(token),now=new Date(),anchor=iso(Date.UTC(now.getUTCFullYear()-2,now.getUTCMonth(),1,0));history.purchases=[permanent({purchasedAt:anchor})];
 assert.equal((await sync(token,'permanent1')).body.coins,6000);assert.equal(await prisma.billingPermanentGrant.count(),12);assert.ok((await prisma.billingReconciliation.findUnique({where:{identityId:b.identity.appUserId}})).nextAttemptAt<=new Date());
 assert.equal((await sync(token)).body.coins,12000);assert.equal((await sync(token)).body.coins,12500);assert.equal(await prisma.billingPermanentGrant.count(),25);assert.equal((await sync(token)).body.coins,12500);
});
it('recovers only available source rewards on refund and restores only actual recovery over repeated cycles',async()=>{
 const {user,token}=await createTestUser();const b=await boot(token);history.purchases=[permanent()];await sync(token);await prisma.user.update({where:{id:user.id},data:{coins:40}});await prisma.billingCreditLot.updateMany({data:{remaining:4}});
 await event(b.identity.appUserId,'refund1','CANCELLATION');let r=await sync(token);assert.equal(r.body.coins,0);assert.equal(r.body.credits.paid,0);assert.equal(r.body.membership.givesAccess,false);
 await event(b.identity.appUserId,'reverse1','REFUND_REVERSED',Date.now()+1000);r=await sync(token);assert.equal(r.body.coins,40);assert.equal(r.body.credits.paid,4);assert.equal(r.body.membership.plan,'permanent');assert.equal(await prisma.billingPermanentGrant.count(),1);
 await event(b.identity.appUserId,'refund2','CANCELLATION',Date.now()+2000);assert.equal((await sync(token)).body.coins,0);await event(b.identity.appUserId,'reverse2','REFUND_REVERSED',Date.now()+3000);assert.equal((await sync(token)).body.coins,40);assert.equal((await boot(token)).credits.paid,4);
});
it('keeps separate monthly access after a permanent refund',async()=>{const {token}=await createTestUser();const b=await boot(token);history.purchases=[monthly(iso(Date.now()-1000),iso(Date.now()+30*86400000)),permanent()];await sync(token);await event(b.identity.appUserId,'refund-monthly','CANCELLATION');const r=await sync(token);assert.equal(r.body.membership.plan,'monthly');assert.equal(r.body.membership.givesAccess,true);assert.equal(r.body.membership.nextRewardAt,null);assert.equal(r.body.coins,500);});
it('keeps one schedule across two stores and preserves access when one source is refunded',async()=>{const {token}=await createTestUser();const b=await boot(token);const first=permanent();history.purchases=[first];await sync(token);const anchor=(await prisma.billingPermanentSchedule.findUnique({where:{identityId:b.identity.appUserId}})).anchorAt;history.purchases.push(permanent({transactionId:'google-perm',appId:'app_android',store:'play_store'}));await sync(token);await event(b.identity.appUserId,'refund-apple','CANCELLATION');const r=await sync(token);assert.equal(r.body.membership.givesAccess,true);assert.equal(r.body.coins,0);assert.equal(await prisma.billingPermanentSchedule.count(),1);assert.deepEqual((await prisma.billingPermanentSchedule.findUnique({where:{identityId:b.identity.appUserId}})).anchorAt,anchor);assert.equal(await prisma.billingPermanentGrant.count(),1);});
it('retains known permanent access during provider outage while deferring all new rewards',async()=>{const {token}=await createTestUser();await boot(token);history.purchases=[permanent()];await sync(token);history=new Error('provider offline');assert.equal((await sync(token)).status,503);const b=await boot(token);assert.equal(b.membership.givesAccess,true);assert.equal(b.coins,500);assert.equal(await prisma.billingPermanentGrant.count(),1);});
it('rejects malformed, unpaid and non-owned permanent activation',async()=>{const {token}=await createTestUser();await boot(token);for(const overrides of [{quantity:2},{purchaseStatus:null},{purchaseStatus:undefined}]){history.purchases=[permanent(overrides)];assert.equal((await sync(token)).status,503);}for(const overrides of [{paid:false},{purchaseStatus:'pending'}]){history.purchases=[permanent(overrides)];const r=await sync(token,'permanent1');assert.equal(r.status,202);assert.equal(r.body.membership.givesAccess,false);assert.equal(r.body.coins,0);}assert.equal(await prisma.billingPermanentGrant.count(),0);});
it('tombstones permanent financial history on deletion and refuses another account restore',async()=>{const {user,token}=await createTestUser();const b=await boot(token);history.purchases=[permanent()];await sync(token);const r=await request(server.baseUrl,'DELETE','/auth/account',{token});assert.equal(r.status,204);assert.ok((await prisma.billingIdentity.findUnique({where:{id:b.identity.appUserId}})).deletedAt);assert.equal(await prisma.billingPermanentSchedule.count(),1);const another=await createTestUser();await boot(another.token);assert.equal((await sync(another.token,'permanent1')).status,409);});
it('never mints unissued refunded backlog and catches it up only after explicit reversal',async()=>{
 const {token}=await createTestUser();const b=await boot(token);history.purchases=[permanent({purchasedAt:iso(Date.now()-65*86400000),purchaseStatus:'refunded',refunded:true})];
 let r=await sync(token,'permanent1');assert.equal(r.status,200);assert.equal(r.body.coins,0);assert.equal(r.body.membership.givesAccess,false);assert.equal(await prisma.billingPermanentGrant.count(),0);
 history.purchases[0].purchaseStatus='owned';history.purchases[0].refunded=false;await event(b.identity.appUserId,'restore-backlog','REFUND_REVERSED',Date.now()+1000);r=await sync(token,'permanent1');assert.equal(r.status,200);assert.equal(r.body.coins,1500);assert.equal(r.body.credits.paid,30);assert.equal(r.body.membership.plan,'permanent');const count=await prisma.billingPermanentGrant.count();await sync(token);assert.equal(await prisma.billingPermanentGrant.count(),count);
});
it('backs off missing known-source verification without advancing owed reward boundaries',async()=>{
 const {token}=await createTestUser();const b=await boot(token),now=new Date();history.purchases=[permanent({purchasedAt:iso(Date.UTC(now.getUTCFullYear()-2,now.getUTCMonth(),1))})];await sync(token);
 const before=await prisma.billingPermanentSchedule.findUnique({where:{identityId:b.identity.appUserId}});history.purchases=[];
 const r=await sync(token);assert.equal(r.status,202);assert.equal(r.body.membership.givesAccess,true);assert.equal(r.body.coins,6000);assert.equal((await prisma.billingPermanentSchedule.findUnique({where:{identityId:b.identity.appUserId}})).nextPeriod,before.nextPeriod);
 const work=await prisma.billingReconciliation.findUnique({where:{identityId:b.identity.appUserId}});assert.ok(work.nextAttemptAt.getTime()>Date.now()+30000);
});
it('does not issue an unpublished-at-refund cosmetic until explicit permanent reversal',async()=>{
 const {token}=await createTestUser();const b=await boot(token);const item=await prisma.shopItem.create({data:{sku:'refund-cosmetic',name:'Month',slot:'HEAD',assetKey:'straw_hat',priceCoins:0}});await prisma.billingCosmeticRelease.create({data:{month:new Date().toISOString().slice(0,7),shopItemId:item.id}});
 history.purchases=[permanent({purchaseStatus:'refunded',refunded:true})];await sync(token);assert.equal(await prisma.billingCosmeticGrant.count(),0);
 history.purchases[0].purchaseStatus='owned';history.purchases[0].refunded=false;await event(b.identity.appUserId,'reverse-cosmetic','REFUND_REVERSED',Date.now()+1000);await sync(token);assert.equal(await prisma.billingCosmeticGrant.count(),1);
});
it('uses paid coverage at permanent purchase even when first reconciliation happens after that subscription expires',async()=>{
 const {token}=await createTestUser();const b=await boot(token),start=iso(Date.now()-65*86400000),end=iso(Date.now()-35*86400000),bought=iso(Date.now()-50*86400000);
 const paid=monthly(start,end);history.subscriptions[0].status='expired';history.subscriptions[0].givesAccess=false;history.purchases=[paid,permanent({purchasedAt:bought})];const r=await sync(token);assert.equal(r.status,200);assert.equal((await prisma.billingPermanentSchedule.findUnique({where:{identityId:b.identity.appUserId}})).anchorAt.toISOString(),end);assert.equal(r.body.coins,1500);
});
it('does not reset the schedule or fund an earlier refunded gap when repurchased',async()=>{
 const {token}=await createTestUser();const b=await boot(token),now=new Date(),anchor=iso(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-2,1));history.purchases=[permanent({purchasedAt:anchor,purchaseStatus:'refunded',refunded:true})];await sync(token);
 history.purchases.push(permanent({transactionId:'repurchase',purchasedAt:iso(Date.now()-1000)}));let r=await sync(token,'repurchase');assert.equal(r.status,200);assert.equal(r.body.coins,0);assert.equal((await prisma.billingPermanentSchedule.findUnique({where:{identityId:b.identity.appUserId}})).anchorAt.toISOString(),anchor);
});
it('fulfills missed permanent rewards through the real worker CLI without a client sync or renewal webhook',async()=>{
 const {mkdtemp,writeFile,rm}=require('node:fs/promises'),path=require('node:path'),{execFile}=require('node:child_process'),{promisify}=require('node:util');const dir=await mkdtemp(path.join(require('node:os').tmpdir(),'permanent-worker-'));
 try{const {token}=await createTestUser();const b=await boot(token),identity=b.identity.appUserId,preload=path.join(dir,'provider.cjs');
 await writeFile(preload,`globalThis.fetch=async url=>{const path=new URL(url).pathname;let body;if(path.endsWith('/products/perm'))body={id:'perm',app_id:'app_ios',store_identifier:'bara_plus_permanent_v1'};else if(path.endsWith('/subscriptions'))body={items:[],next_page:null};else if(path.endsWith('/purchases'))body={items:[{id:'p',customer_id:${JSON.stringify(identity)},original_customer_id:${JSON.stringify(identity)},ownership:'purchased',product_id:'perm',store:'app_store',environment:'production',purchased_at:${Date.now()-35*86400000},quantity:1,status:'owned',store_purchase_identifier:'worker-permanent',revenue_in_usd:{gross:19.99}}],next_page:null};else throw new Error('Unexpected provider URL');return new Response(JSON.stringify(body));};`);
 const run=()=>promisify(execFile)(process.execPath,['--require',preload,'scripts/billing-reconcile.js',`--identity-id=${identity}`],{cwd:path.resolve(__dirname,'../../..'),env:{...process.env,REVENUECAT_PROJECT_ID:config.projectId,REVENUECAT_IOS_APP_ID:config.iosAppId,REVENUECAT_ANDROID_APP_ID:config.androidAppId,REVENUECAT_SECRET_API_KEY:config.secretApiKey,REVENUECAT_WEBHOOK_AUTHORIZATION:config.webhookAuthorization,BILLING_TERMS_URL:config.termsUrl,BILLING_PRIVACY_URL:config.privacyUrl},timeout:20000});
 await run();assert.equal((await boot(token)).coins,1000);await run();assert.equal((await boot(token)).coins,1000);assert.equal(await prisma.billingPermanentGrant.count(),2);
 }finally{await rm(dir,{recursive:true,force:true});}
});
it('defers new rewards on contradictory refunded history after an explicit reversal',async()=>{
 const {token}=await createTestUser();const b=await boot(token),now=new Date();history.purchases=[permanent({purchasedAt:iso(Date.UTC(now.getUTCFullYear()-2,now.getUTCMonth(),1))})];await sync(token);await event(b.identity.appUserId,'cycle-refund','CANCELLATION');await sync(token);await event(b.identity.appUserId,'cycle-reverse','REFUND_REVERSED',Date.now()+1000);await sync(token);assert.equal((await boot(token)).coins,6000);
 history.purchases[0].purchaseStatus='refunded';history.purchases[0].refunded=true;const r=await sync(token);assert.equal(r.status,202);assert.equal(r.body.coins,6000);assert.equal(await prisma.billingPermanentGrant.count(),12);
});
it('enforces immutable schedule and source provenance at the database boundary',async()=>{
 const {token}=await createTestUser();const b=await boot(token);history.purchases=[permanent()];await sync(token);
 await assert.rejects(prisma.billingPermanentSchedule.update({where:{identityId:b.identity.appUserId},data:{anchorAt:new Date()}}));
 const source=await prisma.billingPermanentSource.findFirst();await assert.rejects(prisma.billingPermanentSource.update({where:{purchaseId:source.purchaseId},data:{purchasedAt:new Date()}}));
 const grant=await prisma.billingPermanentGrant.findFirst();await assert.rejects(prisma.billingPermanentGrant.update({where:{id:grant.id},data:{period:100}}));
});
it('retains management for a paused or retrying subscription without giving it access',async()=>{
 const {token}=await createTestUser();await boot(token);history.purchases=[permanent()];await sync(token);
 for(const status of ['paused','in_billing_retry']){monthly(iso(Date.now()-40*86400000),iso(Date.now()-10*86400000));history.subscriptions[0].status=status;history.subscriptions[0].givesAccess=false;history.subscriptions[0].renews=status==='in_billing_retry';
 const r=await sync(token);assert.equal(r.status,200);assert.equal(r.body.membership.plan,'permanent');assert.equal(r.body.membership.subscription.givesAccess,false);assert.equal(r.body.membership.subscription.status,'expired');assert.equal(r.body.membership.subscription.providerStatus,status);assert.equal(r.body.managementUrl,'https://apps.apple.com/account/subscriptions');assert.equal(r.body.coins,500);}
});
it('wakes permanent-only accounts when an operator publishes a monthly cosmetic',async()=>{
 const {token}=await createTestUser();const b=await boot(token);history.purchases=[permanent()];await sync(token);
 await prisma.billingReconciliation.update({where:{identityId:b.identity.appUserId},data:{nextAttemptAt:new Date(Date.now()+6*3600000)}});
 const item=await prisma.shopItem.create({data:{sku:'published-permanent',name:'Month',slot:'HEAD',assetKey:'straw_hat',priceCoins:0}}),{execFile}=require('node:child_process'),{promisify}=require('node:util');
 await promisify(execFile)(process.execPath,['scripts/billing-publish-cosmetic.js',`--month=${new Date().toISOString().slice(0,7)}`,`--item-id=${item.id}`,'--apply'],{cwd:require('node:path').resolve(__dirname,'../../..'),env:process.env,timeout:20000});
 assert.ok((await prisma.billingReconciliation.findUnique({where:{identityId:b.identity.appUserId}})).nextAttemptAt<=new Date());
 await sync(token);assert.equal((await boot(token)).cosmetic.item.id,item.id);
});
it('keeps a resumable subscription visible when the provider omits its management URL',async()=>{const {token}=await createTestUser();await boot(token);history.purchases=[permanent()];monthly(iso(Date.now()-40*86400000),iso(Date.now()-10*86400000));history.subscriptions[0].status='paused';history.subscriptions[0].givesAccess=false;history.subscriptions[0].managementUrl=null;const r=await sync(token);assert.equal(r.status,200);assert.equal(r.body.membership.subscription.plan,'monthly');assert.equal(r.body.membership.subscription.givesAccess,false);assert.equal(r.body.managementUrl,null);});
it('funds one owed schedule from the earliest currently verified eligible source when another is missing',async()=>{
 const {token}=await createTestUser();const b=await boot(token),now=new Date(),anchor=Date.UTC(now.getUTCFullYear()-2,now.getUTCMonth(),1);history.purchases=[permanent({purchasedAt:iso(anchor)})];await sync(token);
 history.purchases=[permanent({transactionId:'second-source',appId:'app_android',store:'play_store',purchasedAt:iso(anchor+1)})];const r=await sync(token,'second-source');assert.equal(r.status,200);assert.equal(r.body.coins,12000);assert.equal(await prisma.billingPermanentSchedule.count(),1);assert.equal(await prisma.billingPermanentGrant.count(),24);
 const source=await prisma.billingPurchase.findFirst({where:{transactionId:'second-source'}}),grant=await prisma.billingPermanentGrant.findFirst({where:{identityId:b.identity.appUserId,period:12}});assert.equal(grant.sourcePurchaseId,source.id);
});
